/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package database.project.homework;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class SchoolView extends javax.swing.JFrame {

    /**
     * Creates new form SchoolView
     */
    public SchoolView() {
        initComponents();
        show_user();
    }
    
    public ArrayList<School> schoolList(){
        
        ArrayList<School> schoolList = new ArrayList<>();
        
        try{
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
	String url="jdbc:sqlserver://localhost:1433; databaseName=SchoolDB; user=Mert2; password=mertusenmez1234";
	Connection con = DriverManager.getConnection(url);
        String query = "SELECT s.SchoolID, s.SchoolName, s.SchoolType, a.SchoolAddressID, a.Street, a.SchoolState, a.Country, a.ZipCode, a.City, a.AddressDetail, p.SchoolPhoneID, p.SchoolPhoneNumber, p.SchoolPhoneType FROM School As s INNER JOIN SCHOOL_ADDRESS AS a ON s.SchoolID = a.SCHOOLSchoolID INNER JOIN SCHOOL_PHONE AS p ON a.SCHOOLSchoolID = p.SCHOOLSchoolID;";    
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        School school;
        while(rs.next())
        {
            school = new School(rs.getInt("SchoolID"), rs.getString("SchoolName"), rs.getString("SchoolType"), rs.getInt("SchoolAddressID"),rs.getString("Street"), rs.getString("SchoolState"),
                    rs.getString("Country"), rs.getInt("ZipCode"), rs.getString("City"), rs.getString("AddressDetail"), rs.getInt("SchoolPhoneID"), rs.getString("SchoolPhoneNumber"), rs.getString("SchoolPhoneType"));
            schoolList.add(school);
        }
        }
        catch(Exception e)
	  {
		  JOptionPane.showMessageDialog(null, e);
	  }
        return schoolList;
    }
    
    public void show_user(){
        
        ArrayList<School> list = schoolList();
        DefaultTableModel model = (DefaultTableModel)SchoolTable.getModel();
        Object[] row = new Object[13];
        for(int i=0; i<list.size(); i++)
        {
            row[0] = list.get(i).getSchoolIDm();
            row[1] = list.get(i).getSchoolNamem();
            row[2] = list.get(i).getSchoolTypem();
            row[3] = list.get(i).getAddressIDm();
            row[4] = list.get(i).getStreetm();
            row[5] = list.get(i).getStatem();
            row[6] = list.get(i).getCountry();
            row[7] = list.get(i).getZipCode();
            row[8] = list.get(i).getCity();
            row[9] = list.get(i).getAddressDetail();
            row[10] = list.get(i).getPhoneID();
            row[11] = list.get(i).getPhoneNumber();
            row[12] = list.get(i).getPhoneType();
                     
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        SchoolIDText = new javax.swing.JTextField();
        SchoolNameText = new javax.swing.JTextField();
        SchoolTypeText = new javax.swing.JTextField();
        AddressIDText = new javax.swing.JTextField();
        StreetText = new javax.swing.JTextField();
        StateText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        SchoolTable = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CountryText = new javax.swing.JTextField();
        ZipCodeText = new javax.swing.JTextField();
        CityText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        AddressDetailText = new javax.swing.JTextField();
        ExitButton = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PhoneIDText = new javax.swing.JTextField();
        PhoneNumberText = new javax.swing.JTextField();
        PhoneTypeText = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        SchoolAddButton = new javax.swing.JButton();
        SchoolDeleteButton = new javax.swing.JButton();
        SchoolUpdateButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("School Operations");

        jLabel2.setText("SchoolID:");

        jLabel3.setText("School Name:");

        jLabel4.setText("School Type:");

        jLabel5.setText("AddressID:");

        jLabel6.setText("Street:");

        jLabel7.setText("State:");

        SchoolTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SchoolID", "SchoolName", "Type", "AddressID", "Street", "State", "Country", "ZipCode", "Cityl", "Address Detai", "PhoneID", "PhoneNumber", "PhoneType"
            }
        ));
        jScrollPane1.setViewportView(SchoolTable);

        jLabel8.setText("Basic Informations:");

        jLabel9.setText("Address Informations:");

        jLabel10.setText("Country:");

        jLabel11.setText("ZipCode:");

        jLabel12.setText("City:");

        jLabel13.setText("Address Detail:");

        ExitButton.setText("X");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        jLabel14.setText("PhoneID:");

        jLabel15.setText("Phone Number:");

        jLabel16.setText("Phone Type:");

        SchoolAddButton.setText("ADD");
        SchoolAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchoolAddButtonActionPerformed(evt);
            }
        });

        SchoolDeleteButton.setText("DELETE");
        SchoolDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SchoolDeleteButtonActionPerformed(evt);
            }
        });

        SchoolUpdateButton.setText("UPDATE");

        ClearButton.setText("CLEAR");
        ClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(SchoolAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SchoolUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SchoolDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SchoolDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SchoolUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SchoolAddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        jLabel17.setText("jLabel17");

        jLabel18.setText("State:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(BackButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitButton))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(209, 209, 209)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addGap(28, 28, 28))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel17)
                                                    .addComponent(jLabel18))
                                                .addGap(43, 43, 43)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(AddressIDText)
                                            .addComponent(StreetText)
                                            .addComponent(StateText, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE))))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(ZipCodeText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CountryText, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CityText, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(SchoolIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(SchoolNameText)
                                    .addComponent(SchoolTypeText)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(329, 329, 329)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(AddressDetailText)
                            .addComponent(PhoneIDText, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PhoneNumberText)
                            .addComponent(PhoneTypeText, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ExitButton)
                    .addComponent(BackButton))
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SchoolIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(AddressIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(CountryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(AddressDetailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(SchoolNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(StreetText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(ZipCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(PhoneIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(SchoolTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(CityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(PhoneNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(StateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(PhoneTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void SchoolAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchoolAddButtonActionPerformed
        try{
          Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
	  String url="jdbc:sqlserver://localhost:1433; databaseName=SchoolDB; user=Mert2; password=mertusenmez1234";
	  Connection con = DriverManager.getConnection(url);
          
          String query0 = "insert into School(SchoolID, SchoolName, SchoolType)values(?,?,?)";
          PreparedStatement pst0 = con.prepareStatement(query0);
          pst0.setString(1, SchoolIDText.getText());
          pst0.setString(2, SchoolNameText.getText());
          pst0.setString(3, SchoolTypeText.getText());
          
          
          String query1 = "insert into SCHOOL_ADDRESS(SchoolAddressID, Street, SchoolState, Country, ZipCode, City, AddressDetail, SCHOOLSchoolID)values(?,?,?,?,?,?,?,?)";
          PreparedStatement pst1 = con.prepareStatement(query1);
          pst1.setString(1, AddressIDText.getText());
          pst1.setString(2, StreetText.getText());
          pst1.setString(3, StateText.getText());
          pst1.setString(4, CountryText.getText());
          pst1.setString(5, ZipCodeText.getText());
          pst1.setString(6, CityText.getText());
          pst1.setString(7, AddressDetailText.getText());
          pst1.setString(8, SchoolIDText.getText());
          
          
          String query2 = "insert into SCHOOL_PHONE(SchoolPhoneID, SchoolPhoneNumber, SchoolPhoneType, SCHOOLSchoolID)values(?,?,?,?)";
          PreparedStatement pst2 = con.prepareStatement(query2);
          pst1.setString(1, PhoneIDText.getText());
          pst1.setString(2, PhoneNumberText.getText());
          pst1.setString(3, PhoneTypeText.getText());
          pst1.setString(4, SchoolIDText.getText());
          
          JOptionPane.showMessageDialog(null, "School Added Succesfully.");
          
        } 
        catch(Exception e)
	  {
		  JOptionPane.showMessageDialog(null, e);
	  }
    }//GEN-LAST:event_SchoolAddButtonActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MenuView MW = new MenuView();
        MW.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_BackButtonActionPerformed

    private void ClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearButtonActionPerformed
        SchoolIDText.setText("");
        SchoolNameText.setText("");
        SchoolTypeText.setText("");
        AddressIDText.setText("");
        StreetText.setText("");
        StateText.setText("");
        CountryText.setText("");
        ZipCodeText.setText("");
        CityText.setText("");
        AddressDetailText.setText("");
        PhoneIDText.setText("");
        PhoneNumberText.setText("");
        PhoneTypeText.setText("");
    }//GEN-LAST:event_ClearButtonActionPerformed

    private void SchoolDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SchoolDeleteButtonActionPerformed
        try{
          Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
	  String url="jdbc:sqlserver://localhost:1433; databaseName=SchoolDB; user=Mert2; password=mertusenmez1234";
	  Connection con = DriverManager.getConnection(url);
          String query = "DELETE FROM School WHERE SchoolID=?";
          PreparedStatement pst = con.prepareStatement(query);
          pst.setString(1, SchoolIDText.getText());
          //ResultSet rs = pst.executeQuery();  BELKİ EKLENEBİLİR.
          JOptionPane.showMessageDialog(null, "School removed Succesfully.");
        }
        catch(Exception e)
	  {
		  JOptionPane.showMessageDialog(null, e);
	  }
    }//GEN-LAST:event_SchoolDeleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchoolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchoolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchoolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchoolView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchoolView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressDetailText;
    private javax.swing.JTextField AddressIDText;
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField CityText;
    private javax.swing.JButton ClearButton;
    private javax.swing.JTextField CountryText;
    private javax.swing.JButton ExitButton;
    private javax.swing.JTextField PhoneIDText;
    private javax.swing.JTextField PhoneNumberText;
    private javax.swing.JTextField PhoneTypeText;
    private javax.swing.JButton SchoolAddButton;
    private javax.swing.JButton SchoolDeleteButton;
    private javax.swing.JTextField SchoolIDText;
    private javax.swing.JTextField SchoolNameText;
    private javax.swing.JTable SchoolTable;
    private javax.swing.JTextField SchoolTypeText;
    private javax.swing.JButton SchoolUpdateButton;
    private javax.swing.JTextField StateText;
    private javax.swing.JTextField StreetText;
    private javax.swing.JTextField ZipCodeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
